### ISSUE TITLE
An error has occurred. "Error: Can not decode an entire message"

### ISSUE THREAD

**Issue by jpg3087** [logstash-plugins/logstash-input-imap#25]
I'm using an imap-input filter. on logstash 5.3
Failing to parse some of the return mails.

The error message is as follows.
===================================================================
===================================================================
[2017-05-02T11: 42: 18,057] [ERROR] [logstash.pipeline] A plugin had an unrecoverable error. Will restart this plugin.
   Plugin: <LogStash :: Inputs :: IMAP type = "returnmail", host => "jira.bizisolution.co.kr", user => "return_myzenic", password => <password>, port => 143, verify_cert => False, secure => false, id => "1bf6e27fedb7acea108c751c76f26a337388c38b-2", enable_metric => true, codec = = False, expunge => false, strip_attachments => false, charset => "UTF-8">, folder => "INBOX", fetch_count => 50, lowercase_headers => true, check_interval = , Content_type => "text / plain">
   Error: Can not decode an entire message, try calling #decoded on the various fields and body or parts if it is a multipart message.
===================================================================
===================================================================

I want to know how to solve it and want to get help.

**Comment by sbabicz** [comment]
I am also having this problem: 
 **Logstash version 6.5.4** 

  Error: Can not decode an entire message, try calling #decoded on the various fields and body or parts if it is a multipart message.
  Exception: NoMethodError
  Stack: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/mail-2.6.6/lib/mail/message.rb:1903:in `decoded'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-imap-3.0.6/lib/logstash/inputs/imap.rb:119:in `parse_mail'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-imap-3.0.6/lib/logstash/inputs/imap.rb:86:in `block in check_mail'
org/jruby/RubyArray.java:1734:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-imap-3.0.6/lib/logstash/inputs/imap.rb:82:in `block in check_mail'
org/jruby/RubyArray.java:1778:in `each_slice'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-imap-3.0.6/lib/logstash/inputs/imap.rb:80:in `check_mail'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-imap-3.0.6/lib/logstash/inputs/imap.rb:69:in `block in run'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/interval.rb:20:in `interval'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-imap-3.0.6/lib/logstash/inputs/imap.rb:68:in `run'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:409:in `inputworker'


It happens when I am processing return messages after using header: Disposition-Notification-To:

**Comment by BobbyGR** [comment]
Anyone know if this was resolved?

**Comment by enumanc** [comment]
Same issue on my side. Did you find a solution ?

**Comment by eabrilmena** [comment]
Has anyone found how to solve this? Thanks in advance

**Comment by M9k** [comment]
Try to use:
strip_attachments => true

**Comment by dcl-fred** [comment]
Hello, thank you @M9k for your reply. This did not help on my side. Still the same issue...

**Comment by M9k** [comment]
> Hello, thank you @M9k for your reply. This did not help on my side. Still the same issue...

If you post your configuration (without the passwords) I'll check if there is something that differ from my configuration.
Which IMAP server are you using? I use Office365 and IBM Domino and it works fine.

**Comment by enumanc** [comment]
I am using Gmail:
`input {
  imap {
    host => "imap.gmail.com"
    user => "******"
    password => "*******"
    port => 993
    secure => true
    verify_cert => false
    #content_type => "text/plain"
    folder => "TOTO"
    check_interval => 60
    tags => ["toto"]
  }
}
`

**Comment by Ot92** [comment]
Having "content_type" and "strip_attachments" as the first two entries worked for me.
  
imap {
    content_type => "multipart/alternative"
    strip_attachments => true
    host => "imap.gmail.com"
    password => "*****"
    user => "*****"
    port => 993
    secure => true
    verify_cert => false
    check_interval => 5
  }
